project:
  type: website
  output-dir: docs
  resources:
   - "*.csv"
   - "*.csv.gz"
   - "*.xlsx"

  preview:
    port: 4200
    browser: true


website:
  title: "Eduquant course slides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: moon
    css: webpage_styles.css
    toc: true



