project:
  type: website
  output-dir: docs
  
  resources:
   - "*.csv"
   - "*.csv.gz"
   - "*.xlsx"
   - "*.pdf"

  preview:
    port: 4200
    browser: true


website:
  title: "Eduquant course slides"
  favicon: /media/icon.png
  image: /media/logo_transparent.svg
  cookie-consent: true
  page-footer: "(all materials on this site) copyright 2022, Pieter van den Berg" 
  navbar:
    logo: /media/icon.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: webpage_styles.css
    toc: true



