project:
  type: website
  output-dir: docs

website:
  title: "eduquant-courses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: moon
    css: styles.css
    toc: true



