project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true


website:
  title: "eduquant-courses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: moon
    css: webpage_styles.css
    toc: true



