---
title: "MoC & Downturn LGD"
subtitle: "Day 1"
# author: "Pieter van den Berg"
date: last-modified
date-format: long
format: eduquant-slides-revealjs
---

{{< include ../_sections/introductions.qmd >}}

# Course Outline

## Course outline

::: {.columns #vcenter}
::: {.column width="45%" }
[General topics]{style="color: darkseagreen;"}
:::

::: {.column width="55%"}
IRB Regulation

Risk Parameter quantification
:::
:::

::: {.columns}
::: {.column width="45%"}
[Margin of Conservatism]{style="color: darkseagreen;"}
:::

::: {.column width="55%"}
Deficiencies

Appropriate Adjustments

MoC Quantification
:::
:::

::: {.columns}
::: {.column width="45%"}
[Downturn LGD]{style="color: darkseagreen;"}
:::

::: {.column width="55%"}
Downturn Identification

Downturn LGD Quantification
:::
:::

## Day 1

::: {.columns}
::: {.column width="40%"}
*13:00*

*13:30*

*14:15*

*15:00*

*15:15*

*16:00*

*16:45*
:::

::: {.column width="60%"}
Introduction

Overview of IRB Regulation

Risk Parameter Quantification

*Break*

LGD Quantification

Margin of Conservatism

Day Recap
:::
:::

## Day 2

::: {.columns}
::: {.column width="40%"}
*13:00*

*13:30*

*14:15*

*15:00*

*15:15*

*16:00*

*16:45*
:::

::: {.column width="60%"}
Quiz & Recap

General Estimation Error

Deficiencies

*Break*

Appropriate Adjustments

Additional Uncertainties

Case Study Explanation
:::
:::

## Day 3

::: {.columns}
::: {.column width="40%"}
*13:00*

*13:45*

*14:30*

*15:00*

*15:15*

*16:00*

*16:45*
:::

::: {.column width="60%"}
Recap & Discussion Case Study

DT LGD Conceptual Basis

Nature of an Economic Downturn

*Break*

Severity & Duration

DT LGD Quantification

Case Study Explanation
:::
:::

## Day 4

::: columns
::: {.column width="40%"}
*13:00*

*13:45*

*14:30*

*15:00*

*15:15*

*16:00*

*16:45*
:::

::: {.column width="60%"}
Recap & Discussion Case Study

Observed Impact Assessments

Extrapolation & Haircut Approaches

*Break*

DT LGD Calibration

Course Recap & Quiz

Q&A
:::
:::

# Introduction

## Overview of IRB Regulation

::: {.notes}
Diagram: basel -> CRR/RTS/GL  -> EGIM ]
:::

## Example: Observed default rate 

::: {.notes}
Show Basel CRE36.64, article 4(78), GL PD/LGD par 73ff 
:::

## Implementing IRB

::: {.notes}
Diagram: [ CRR/RTS/GL + EGIM ] -> policy -> standard -> rating system
:::

## Example: Review of estimates


::: {.notes}
Maybe find a simpler example
:::

## Reading regulation

::: {.notes}
Defined versus undefined
Principle-based versus rule-based
:::

## Rating Systems

::: {.notes}
multiple slides with definitions

exposure class
rating system
type of exposure
range of application
IRB approval
:::

## Risk Parameter Estimation

::: {.notes}
Diagram: differentiation -> quantification
:::

## Risk Parameter Quantification

::: {.notes}
Diagram: Type of Exposures -> RDS -> Initial Calibration Target -> Appr. Adjusted Target

Par 12 PD&LGD

:::


## Reference Data Sets

::: {.notes}
Estimation RDS: Type of Exposures -> Comparable Exposures, Reference Dates -> RDS

Application Portfolio RDS: Recent Date, Actual Portfolio
:::

## Reference Dates & Observation Windows

::: {.notes}
Diagrams: discrete timelines with labels

PD:   R => [o o o o o D . . . . . . . ]
           performing default recovery
LGD: R => [o o o o o o D d d d d ... L]
CCF:  R => o o o o o D ...

In-default LGD/CCF: D ... R [... R[ ... L ]]...
:::


# *Break*

# LGD Quantification

## Realised LGD Calculation

:::{.notes}
Formula Realised LGD = Actual exposure at default - discounted recoveries / 

:::

# Margin of Conservatism

## Conceptual Basis